---
- name: Create Elasticsearch-Kibana Instance
  hosts: localhost
  connection: local

  tasks:
    - name: Create Instance
      gce:
        instance_names: elasticsearch-kibana-1
        zone: asia-southeast1-a
        machine_type: g1-small
        image: ubuntu-1804
        state: present
        tags:
          - bastion
          - sshable
        network: wildtype
        subnetwork: wildtype-application
      register: created_instance

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ created_instance.instance_data }}"

    - name: Save host
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: elasticsearch_kibana
      with_items: "{{ created_instance.instance_data }}"
        
- name: pepare new host
  hosts: elasticsearch_kibana
  gather_facts: no
  become: yes

  # ansible needs /usr/bin/python in target hosts to gather facts
  # meanwhile ubuntu 1804 only have python3 by default
  # so far this is the only hacks that worked :(

  tasks:
    - name: Install python2 
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Setup elasticsearch and kibana
  hosts: elasticsearch_kibana

  roles:
    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: no
      oracle_java_apt_repository: "ppa:webupd8team/java"
      oracle_java_cache_valid_time: 3600
      oracle_java_deb_package: 'oracle-java8-installer'
      oracle_java_debconf_package_default: 'oracle-java8-set-default'
      oracle_java_home: "/usr/lib/jvm/java-8-oracle"
      oracle_java_set_as_default: yes
      oracle_java_state: latest

    - role: elasticsearch
    - role: kibana
