---
- name: Download Elasticsearch Binary Package
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.deb
    dest: /tmp/elasticsearch-6.4.2.deb

- name: Install Elasticsearch
  apt:
    deb: /tmp/elasticsearch-6.4.2.deb
  become: yes

- name: Make sure elasticsearch service is started
  systemd:
    name: elasticsearch
    state: started
  become: yes
